# Copyright 2026 Codesnap
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from datetime import timedelta

from odoo import fields
from odoo.tests.common import TransactionCase, tagged

from odoo.addons.spreadsheet_public_share_oca.models.public_share import (
    _col_letter,
    _parse_ref,
    _resolve_display,
)


@tagged("post_install", "-at_install")
class TestPublicShareHelpers(TransactionCase):
    """Pure helper functions used by the engine-less HTML preview."""

    def test_parse_ref_roundtrip(self):
        # A1 -> (0, 0); Z1 -> (25, 0); AA1 -> (26, 0)
        self.assertEqual(_parse_ref("A1"), (0, 0))
        self.assertEqual(_parse_ref("Z1"), (25, 0))
        self.assertEqual(_parse_ref("AA1"), (26, 0))
        self.assertEqual(_parse_ref("B3"), (1, 2))

    def test_parse_ref_invalid(self):
        self.assertEqual(_parse_ref("not-a-ref"), (0, 0))

    def test_col_letter_roundtrip(self):
        for col in (0, 1, 25, 26, 27, 51, 52, 701, 702):
            letter = _col_letter(col)
            parsed_col, _row = _parse_ref(letter + "1")
            self.assertEqual(parsed_col, col, f"roundtrip failed for col {col}")

    def test_resolve_display_literal(self):
        # Plain content is shown verbatim, not flagged as computed.
        self.assertEqual(_resolve_display("Hello"), ("Hello", False))
        self.assertEqual(_resolve_display(""), ("", False))
        self.assertEqual(_resolve_display(None), ("", False))

    def test_resolve_display_translation_label(self):
        # A pure translation label resolves to its literal text.
        self.assertEqual(_resolve_display('=_t("Total")'), ("Total", False))

    def test_resolve_display_formula(self):
        # Any other formula cannot be evaluated server-side -> flagged computed.
        display, computed = _resolve_display("=SUM(A1:A9)")
        self.assertEqual(display, "")
        self.assertTrue(computed)


@tagged("post_install", "-at_install")
class TestPublicShare(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.Share = cls.env["spreadsheet.public.share"]
        cls.ICP = cls.env["ir.config_parameter"].sudo()
        cls.spreadsheet = cls.env["spreadsheet.spreadsheet"].create(
            {"name": "Test Sheet"}
        )

    def _new_share(self, **vals):
        base = {"name": "Link", "spreadsheet_id": self.spreadsheet.id}
        base.update(vals)
        return self.Share.create(base)

    def test_token_autogenerated_and_url(self):
        share = self._new_share()
        self.assertTrue(share.token)
        self.assertIn(share.token, share.share_url)

    def test_verify_token_happy_path_counts_once(self):
        share = self._new_share()
        rec = self.Share.verify_token(share.token)
        self.assertEqual(rec, share)
        self.assertEqual(share.view_count, 1)
        self.assertTrue(share.last_viewed)

    def test_verify_token_no_count(self):
        # Downloads must not inflate the page view counter.
        share = self._new_share()
        self.Share.verify_token(share.token, count=False)
        self.assertEqual(share.view_count, 0)

    def test_verify_token_unknown(self):
        self.assertFalse(self.Share.verify_token("does-not-exist"))
        self.assertFalse(self.Share.verify_token(None))

    def test_verify_token_inactive(self):
        share = self._new_share(active=False)
        self.assertFalse(self.Share.verify_token(share.token))

    def test_verify_token_expired(self):
        share = self._new_share(expires_at=fields.Datetime.now() - timedelta(days=1))
        self.assertFalse(self.Share.verify_token(share.token))

    def test_verify_token_password(self):
        share = self._new_share(password="s3cret")
        self.assertFalse(self.Share.verify_token(share.token))
        self.assertFalse(self.Share.verify_token(share.token, "wrong"))
        self.assertEqual(self.Share.verify_token(share.token, "s3cret"), share)

    def test_default_expires_at_from_settings(self):
        self.ICP.set_int("spreadsheet_public_share.default_expiry_days", 7)
        try:
            share = self._new_share()
            self.assertTrue(share.expires_at)
            delta = share.expires_at - fields.Datetime.now()
            self.assertGreater(delta, timedelta(days=6))
            self.assertLess(delta, timedelta(days=8))
        finally:
            self.ICP.set_int("spreadsheet_public_share.default_expiry_days", 0)

    def test_default_allow_download_from_settings(self):
        self.ICP.set_bool("spreadsheet_public_share.allow_download_default", True)
        try:
            self.assertTrue(self._new_share().allow_download)
        finally:
            self.ICP.set_bool("spreadsheet_public_share.allow_download_default", False)

    def test_get_rendered_sheets_skips_data_sheet(self):
        self.spreadsheet.spreadsheet_raw = {
            "sheets": [
                {"name": "Data", "cells": {"A1": {"content": "secret"}}},
                {"name": "Report", "cells": {"A1": {"content": "Visible"}}},
            ]
        }
        rendered = self._new_share().get_rendered_sheets()
        names = [s["name"] for s in rendered]
        self.assertEqual(names, ["Report"])

    def test_get_rendered_sheets_merges_and_hidden(self):
        self.spreadsheet.spreadsheet_raw = {
            "sheets": [
                {
                    "name": "Report",
                    "cells": {
                        "A1": {"content": "Title"},
                        "B1": {"content": "dropped"},
                    },
                    "merges": ["A1:B1"],
                }
            ]
        }
        rendered = self._new_share().get_rendered_sheets()
        first_row_cells = rendered[0]["rows"][0]["cells"]
        # B1 is hidden by the merge, so only the anchor cell remains.
        self.assertEqual(len(first_row_cells), 1)
        self.assertEqual(first_row_cells[0]["colspan"], 2)

    def test_get_rendered_sheets_truncation_flag(self):
        # A cell far beyond the cap trips the truncation flag.
        self.spreadsheet.spreadsheet_raw = {
            "sheets": [
                {
                    "name": "Big",
                    "cells": {
                        "A1": {"content": "x"},
                        "AZ200": {"content": "y"},
                    },
                }
            ]
        }
        rendered = self._new_share().get_rendered_sheets()
        self.assertTrue(rendered[0]["truncated"])

    def test_get_rendered_sheets_not_truncated(self):
        self.spreadsheet.spreadsheet_raw = {
            "sheets": [{"name": "Small", "cells": {"A1": {"content": "x"}}}]
        }
        rendered = self._new_share().get_rendered_sheets()
        self.assertFalse(rendered[0]["truncated"])
