# Copyright 2026 Codesnap
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import base64
from datetime import timedelta

from odoo import fields
from odoo.exceptions import AccessError, ValidationError
from odoo.tests.common import TransactionCase, new_test_user, tagged

from .fixtures import export_data_workbook, legacy_workbook


@tagged("post_install", "-at_install")
class TestPublicShare(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.Share = cls.env["spreadsheet.public.share"]
        cls.ICP = cls.env["ir.config_parameter"].sudo()
        cls.spreadsheet = cls.env["spreadsheet.spreadsheet"].create(
            {"name": "Test Sheet"}
        )
        cls.owner = new_test_user(
            cls.env,
            login="share_owner",
            groups="base.group_user,spreadsheet_oca.group_user",
        )
        cls.other_user = new_test_user(
            cls.env,
            login="share_other",
            groups="base.group_user,spreadsheet_oca.group_user",
        )
        cls.manager = new_test_user(
            cls.env,
            login="share_manager",
            groups="base.group_user,spreadsheet_oca.group_manager",
        )
        cls.owned_spreadsheet = cls.env["spreadsheet.spreadsheet"].create(
            {"name": "Owner Sheet", "owner_id": cls.owner.id}
        )

    def _new_share(self, **vals):
        base = {"name": "Link", "spreadsheet_id": self.spreadsheet.id}
        base.update(vals)
        return self.Share.create(base)

    # --- token / counters -------------------------------------------------

    def test_token_autogenerated_and_url(self):
        share = self._new_share()
        self.assertTrue(share.token)
        self.assertIn(share.token, share.share_url)

    def test_verify_token_happy_path_counts_once(self):
        share = self._new_share()
        rec = self.Share._verify_token(share.token)
        self.assertEqual(rec, share)
        self.assertEqual(share.view_count, 1)
        self.assertTrue(share.last_viewed)

    def test_verify_token_no_count(self):
        # Downloads must not inflate the page view counter.
        share = self._new_share()
        self.Share._verify_token(share.token, count=False)
        self.assertEqual(share.view_count, 0)

    def test_verify_token_unknown(self):
        self.assertFalse(self.Share._verify_token("does-not-exist"))
        self.assertFalse(self.Share._verify_token(None))

    def test_verify_token_inactive(self):
        share = self._new_share(active=False)
        self.assertFalse(self.Share._verify_token(share.token))

    def test_verify_token_expired(self):
        share = self._new_share(expires_at=fields.Datetime.now() - timedelta(days=1))
        self.assertFalse(self.Share._verify_token(share.token))

    def test_verify_token_is_not_rpc_callable(self):
        # A public verify_token let any internal user brute-force a link
        # password over RPC, bypassing the controller throttle.
        self.assertFalse(hasattr(self.Share, "verify_token"))

    # --- password ------------------------------------------------------------

    def test_verify_token_password(self):
        share = self._new_share(password="s3cret")
        self.assertFalse(self.Share._verify_token(share.token))
        self.assertFalse(self.Share._verify_token(share.token, "wrong"))
        self.assertEqual(self.Share._verify_token(share.token, "s3cret"), share)

    def test_password_is_stored_hashed(self):
        share = self._new_share(password="çok-gizli")
        stored = share.sudo().password_hash
        self.assertTrue(stored.startswith("$pbkdf2-sha512$"), stored)
        self.assertNotIn("çok-gizli", stored)
        # The write-only field never gives the password back (drop the value
        # the inverse left in the cache during create before reading it).
        share.invalidate_recordset(["password"])
        self.assertFalse(share.password)
        self.assertTrue(share.has_password)
        self.assertTrue(share._check_share_password("çok-gizli"))
        self.assertFalse(share._check_share_password("cok-gizli"))

    def test_password_hash_not_readable_by_users(self):
        share = self._new_share(password="s3cret")
        share.created_by_id = self.owner
        with self.assertRaises(AccessError):
            share.with_user(self.owner).read(["password_hash"])
        with self.assertRaises(AccessError):
            share.with_user(self.manager).read(["password_hash"])

    def test_empty_password_keeps_current_one(self):
        share = self._new_share(password="s3cret")
        share.write({"password": False, "name": "Renamed"})
        self.assertTrue(share.has_password)
        self.assertTrue(share._check_share_password("s3cret"))

    def test_remove_password(self):
        share = self._new_share(password="s3cret")
        share.action_remove_password()
        self.assertFalse(share.has_password)
        self.assertEqual(self.Share._verify_token(share.token), share)

    def test_legacy_plaintext_value_is_upgraded(self):
        # A value stored before hashing existed still opens the link once and
        # is replaced by a hash (safety net next to the migration script).
        share = self._new_share()
        share.sudo().password_hash = "legacy-plain"
        self.assertFalse(share._check_share_password("nope"))
        self.assertTrue(share._check_share_password("legacy-plain"))
        self.assertTrue(share.sudo().password_hash.startswith("$pbkdf2-sha512$"))

    def test_duplicate_keeps_password(self):
        share = self.Share.with_user(self.owner).create(
            {
                "name": "Protected",
                "spreadsheet_id": self.owned_spreadsheet.id,
                "password": "s3cret",
            }
        )
        duplicate = share.copy()
        self.assertNotEqual(duplicate.token, share.token)
        self.assertEqual(duplicate.created_by_id, self.owner)
        # A duplicate of a protected link must not open without the password.
        self.assertTrue(duplicate.has_password)
        self.assertTrue(duplicate._check_share_password("s3cret"))
        self.assertFalse(duplicate._check_share_password("wrong"))
        self.assertNotEqual(duplicate._get_access_grant(), share._get_access_grant())
        # An explicit new password wins over the copied one.
        renewed = share.copy({"password": "n3w"})
        self.assertTrue(renewed._check_share_password("n3w"))
        self.assertFalse(renewed._check_share_password("s3cret"))

    def test_password_grant_changes_with_password_and_token(self):
        share = self._new_share(password="one")
        grant = share._get_access_grant()
        share.password = "two"
        self.assertNotEqual(share._get_access_grant(), grant)
        grant = share._get_access_grant()
        share.action_regenerate_token()
        self.assertNotEqual(share._get_access_grant(), grant)

    # --- access rights -------------------------------------------------------

    def test_non_owner_cannot_read_another_users_share(self):
        share = self.Share.with_user(self.owner).create(
            {"name": "Owner link", "spreadsheet_id": self.owned_spreadsheet.id}
        )
        self.assertEqual(share.created_by_id, self.owner)
        # The owner sees and edits their own link.
        self.assertEqual(share.with_user(self.owner).token, share.token)
        share.with_user(self.owner).write({"name": "Renamed by owner"})
        # Another spreadsheet user can neither find nor read nor change it.
        other_env_share = self.Share.with_user(self.other_user)
        self.assertFalse(other_env_share.search([("id", "=", share.id)]))
        with self.assertRaises(AccessError):
            share.with_user(self.other_user).read(["token"])
        with self.assertRaises(AccessError):
            share.with_user(self.other_user).write({"allow_download": True})
        # A Spreadsheet manager supervises every link.
        self.assertEqual(
            self.Share.with_user(self.manager).search([("id", "=", share.id)]),
            share,
        )

    def test_cannot_share_unreadable_spreadsheet(self):
        with self.assertRaises(ValidationError):
            self.Share.with_user(self.other_user).create(
                {"name": "Leak", "spreadsheet_id": self.owned_spreadsheet.id}
            )

    def test_reader_cannot_share_spreadsheet(self):
        self.owned_spreadsheet.reader_ids = [(4, self.other_user.id)]
        with self.assertRaises(ValidationError):
            self.Share.with_user(self.other_user).create(
                {"name": "Reader link", "spreadsheet_id": self.owned_spreadsheet.id}
            )

    def test_cannot_move_share_to_unwritable_spreadsheet(self):
        own_spreadsheet = (
            self.env["spreadsheet.spreadsheet"]
            .with_user(self.other_user)
            .create({"name": "Other's own sheet"})
        )
        share = self.Share.with_user(self.other_user).create(
            {"name": "Mine", "spreadsheet_id": own_spreadsheet.id}
        )
        with self.assertRaises(ValidationError):
            share.write({"spreadsheet_id": self.owned_spreadsheet.id})

    def test_cannot_share_through_default_context(self):
        # spreadsheet_id coming from a default_* context key is checked too.
        with self.assertRaises(ValidationError):
            self.Share.with_user(self.other_user).with_context(
                default_spreadsheet_id=self.owned_spreadsheet.id
            ).create({"name": "Leak through a default"})

    def test_link_stops_when_creator_loses_edit_access(self):
        self.owned_spreadsheet.contributor_ids = [(4, self.other_user.id)]
        share = self.Share.with_user(self.other_user).create(
            {"name": "Contributor link", "spreadsheet_id": self.owned_spreadsheet.id}
        )
        self.assertEqual(self.Share._get_live_share(share.token), share)
        self.owned_spreadsheet.contributor_ids = [(3, self.other_user.id)]
        self.assertFalse(self.Share._get_live_share(share.token))
        self.assertFalse(self.Share._verify_token(share.token))

    def test_link_created_without_the_check_never_opens(self):
        # A link created before the write-access check existed (the H2 exploit)
        # stays in the database after the upgrade but is never served.
        share = self._new_share(
            spreadsheet_id=self.owned_spreadsheet.id,
            created_by_id=self.other_user.id,
            allow_download=True,
        )
        self.assertFalse(self.Share._get_live_share(share.token))
        share.created_by_id = self.owner
        self.assertEqual(self.Share._get_live_share(share.token), share)

    def test_creator_check_ignores_website_company_context(self):
        # The public website request carries allowed_company_ids of the website;
        # it must neither crash nor decide the access of the link creator.
        share = self.Share.with_user(self.owner).create(
            {"name": "Mine", "spreadsheet_id": self.owned_spreadsheet.id}
        )
        other_company = self.env["res.company"].create({"name": "Other Co"})
        Share = self.Share.with_context(allowed_company_ids=[other_company.id])
        self.assertEqual(Share._get_live_share(share.token), share)

    def test_only_managers_change_token_or_creator(self):
        share = self.Share.with_user(self.owner).create(
            {"name": "Mine", "spreadsheet_id": self.owned_spreadsheet.id}
        )
        with self.assertRaises(AccessError):
            share.write({"token": "weak"})
        with self.assertRaises(AccessError):
            share.write({"created_by_id": self.other_user.id})
        with self.assertRaises(AccessError):
            self.Share.with_user(self.owner).create(
                {
                    "name": "Chosen token",
                    "spreadsheet_id": self.owned_spreadsheet.id,
                    "token": "weak",
                }
            )
        # Writing back the current values is harmless.
        share.write({"token": share.token, "created_by_id": self.owner.id})
        # The owner still regenerates the token the normal way.
        old_token = share.token
        share.action_regenerate_token()
        self.assertNotEqual(share.token, old_token)
        # A Spreadsheet manager can hand the link over.
        share.with_user(self.manager).write({"created_by_id": self.other_user.id})
        self.assertEqual(share.sudo().created_by_id, self.other_user)

    def test_contributor_and_manager_can_share(self):
        self.owned_spreadsheet.contributor_ids = [(4, self.other_user.id)]
        share = self.Share.with_user(self.other_user).create(
            {"name": "Contributor link", "spreadsheet_id": self.owned_spreadsheet.id}
        )
        self.assertTrue(share)
        self.assertTrue(
            self.Share.with_user(self.manager).create(
                {"name": "Manager link", "spreadsheet_id": self.owned_spreadsheet.id}
            )
        )

    # --- defaults ------------------------------------------------------------

    def test_default_expires_at_from_settings(self):
        self.ICP.set_int("spreadsheet_public_share.default_expiry_days", 7)
        try:
            share = self._new_share()
            self.assertTrue(share.expires_at)
            delta = share.expires_at - fields.Datetime.now()
            self.assertGreater(delta, timedelta(days=6))
            self.assertLess(delta, timedelta(days=8))
        finally:
            self.ICP.set_int("spreadsheet_public_share.default_expiry_days", 0)

    def test_default_allow_download_from_settings(self):
        self.ICP.set_bool("spreadsheet_public_share.allow_download_default", True)
        try:
            self.assertTrue(self._new_share().allow_download)
        finally:
            self.ICP.set_bool("spreadsheet_public_share.allow_download_default", False)

    # --- preview through the model --------------------------------------------

    def test_rendered_sheets_from_export_data(self):
        self.spreadsheet.spreadsheet_raw = export_data_workbook()
        rendered = self._new_share()._get_rendered_sheets()
        self.assertEqual([sheet["name"] for sheet in rendered], ["Report"])
        first_row = rendered[0]["rows"][0]["cells"]
        self.assertEqual(first_row[0]["display"], "Quarter")
        self.assertIn("background-color:#875a7b;", first_row[0]["style_css"])
        # The hidden row 6 is left out.
        self.assertEqual(len(rendered[0]["rows"]), 5)

    def test_undecodable_workbook_degrades(self):
        share = self._new_share()
        not_json = base64.b64encode(b"not json").decode()
        self.spreadsheet.spreadsheet_binary_data = not_json
        self.assertIsNone(share._get_spreadsheet_data())
        self.assertEqual(share._get_rendered_sheets(), [])

    def test_rendered_sheets_from_legacy_format(self):
        self.spreadsheet.spreadsheet_raw = legacy_workbook()
        rendered = self._new_share()._get_rendered_sheets()
        self.assertEqual(rendered[0]["rows"][0]["cells"][0]["display"], "Title")
